### ISSUE TITLE
Show date of data in header

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc-web#26]
The [header](https://github.com/pkiraly/metadata-qa-marc-web/blob/main/templates/common/header.tpl) shows name of catalog and number of records. It should also show the date of the data (YYYY-MM-DD) because most catalog data changes regularly, so its clear how old the analysis is.

**Comment by pkiraly** [comment]
@nichtich Good suggestion. The question is what should be the source of this information. For the Gent catalogue the process automatically generate a file with the date of the download. For K10plus records we could use the last file modification date. Is that OK, or do you have a better solution?

**Comment by nichtich** [comment]
The date should be [https://github.com/pkiraly/metadata-qa-marc#configuration-1](configured) with the data because modification time of files is often newer due to copying the files from one server to another.

**Comment by pkiraly** [comment]
Thanks! Good idea, I will implement it.
