### ISSUE TITLE
Make user interface translatable

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-marc-web#40]

**Comment by nichtich** [comment]
This is mostly done. As far as I can tell only the table of issues needs some work to allow for translation.

**Comment by pkiraly** [comment]
I added a number of translations to the issues/Probleme tab. Could you please check the translations there?

**Comment by nichtich** [comment]
The interface is made translatable and most of it has been translated to German. For missing parts please create a specific issue, if needed.
