### ISSUE TITLE
PICA: Support search and replace workflow

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc-web#57]
I'm not sure whether this use case requires changes in the UI apart from a link.

Given the terms list, one can spot an error, e.g. the code "dnb" should be "DNB" instead. To correct this, it needs 

- a list of PPN for records with this error 
- the PICA+ field and subfield where the error origins from
- the subfield value to replace (e.g. "dnb")
- the subfield value to replace with (e.g. "DNB")
- A script to generate correction in PICA Patch format

MQA web interface may help to pass the information to a script or another web service.

**Comment by pkiraly** [comment]
@nichtich We should talk about the details of this, now it is not clear if i) you would like MQA to accept a PICA patch or ii) to help in generation of a PICA patch (an if yes: where, on web UI or on CLI?) or iii) both?

**Comment by nichtich** [comment]
A downloadable list of PPN of records that have selected value in selected field is enough to start with.

**Comment by nichtich** [comment]
This may be solved with https://github.com/pkiraly/metadata-qa-marc-web/issues/69. Common use cases are 

- there is an undefined field or subfield, so get a list of records (PPN) containing this (sub)field
- more generic: get a list of records (PPN) having a specific error
- A common typo has been found in a specific subfield, e.g. language code `germ` instead of `ger`. Get a list of all records having this value in the field

By the way, these lists could also be generated from the original data dump with other tools such as pica-rs.

**Comment by pkiraly** [comment]
Solved with #69. Reopen it if you feel that that solution does not solve this problem.
