### ISSUE TITLE
Add download link in search result

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc-web#69]
The `tab=data` view with search result should provide a link to download the result (or at least the first *n* records if performance is a problem) in form of a simple list of record identifiers (header-less TSV file).

**Comment by pkiraly** [comment]
Should the content be only the record ID, or should it be the whole record? The whole record is saved as JSON in the search engine.

**Comment by nichtich** [comment]
Just the record ID.
