### ISSUE TITLE
Questions on histograms

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc-web#85]
Histogram in classifications tab does "x: number of subjects in one record" actually mean "x: number of subject fields per record"? I'm asking because some fields may contain repeated subfields so one field can include mutliple subjects. But this depends on the specific subfield, so I guess MQA just counts fields. In this case the text should be changed.

**Comment by pkiraly** [comment]
Let me investigate the code.

**Comment by pkiraly** [comment]
You are right, it counts field occurrences. In MARC the subject indexing term are not repeatable, and I just see that in PICA they might be repeatable. We should change it. The question: how urgent do you think it is?

**Comment by nichtich** [comment]
Just adjust the documentation. Counting specific subfields would need to first define these subfields and the current metrics give useful results as well.
