### ISSUE TITLE
authority tab crashes

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc-web#88]
Opening the authority tab with K10plus data at our local instance crashes with following error message:

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 64596008 bytes) in /srv/apps/qac/metadata-qa-marc-web/libs/smarty-3.1.44/libs/sysplugins/smarty_internal_template.php on line 233, referer: http://data.gbv.de/kxp/qa-catalogue/?tab=history&lang=de

this may be caused by faulty input data or a memory leak, looks like some infinite recursion.

**Comment by pkiraly** [comment]
Is it with a limited number of records?
The simple solution is to increase the amount of memory for PHP. You should look for a file name php.ini, e.g `/etc/php/7.X/apache2/php.ini` (X refers to a particular PHP version). There are more such files, one for command line and one for apache. We need the later one (the command line one is like `/etc/php/7.X/cli/php.ini`).
Search for a line like this:
```
memory_limit = 128M
```
1. increase the size (e.g. double it)
2. save the file
3. restart Apache2
